const String INFO_MIN_VALUES = "globalEmotionMin";
const String INFO_MAX_VALUES = "globalEmotionMax";
const String INFO_SERIES_LABELS = "seriesLabels";
const String INFO_LEN_TIME = "temporalLen";
const String INFO_LEN_INSTANCE = "instanceLen";
const String INFO_LEN_VARIABLES = "variablesLen";
const String INFO_DATES = "dates";
const String INFO_LABELS = "labels";
const String INFO_IS_DATED = "isDated";
const String INFO_DOWNSAMPLE_RULES = "downsampleRules";
const String INFO_IDS = "ids";
const INFO_CATEGORICAL_LABELS = "categoricalLabels";
const INFO_NUMERICAL_LABELS = "numericalLabels";
const INFO_IDENTIFIERS_LABELS = "identifiersLabels";
const INFO_TYPE = "type"; // * either 'dimensional' or 'categorical'
const INFO_DIMENSIONS = "dimensions"; // * only if type is dimensional

const String SETTINGS_ALPHAS = "alphas";
const String SETTINGS_EMOTIONS_LABELS = "emotionLabels";
const String SETTINGS_LOWER_BOUNDS = "globalEmotionLowerBound";
const String SETTINGS_UPPER_BOUNDS = "globalEmotionUpperBound";
const String SETTINGS_START_POSITION = "globalStartPosition";
const String SETTINGS_WINDOW_LENGTH = "globalWindowLength";
