enum TemporalVisualization {
  LINEAR_CHART,
  STACKED_CHART,
  POLAR_BARS,
  TEMPORAL_GLYPH,
  TEMPORAL_TUNNEL,
  TAGGED_TUNNEL
}

enum NonTemporalVisualization {
  DIMENSIONAL_SCATTERPLOT,
  CATEGORICAL_SCATTERPLOT,
  INSTANT_GLYPH,
  INSTANT_GLYPH_SINGLE,
  POLAR_LINES
}

// enum MultipleView { LIST, GRID, SCATTERPLOT }
enum MultipleView { LIST, GRID }

enum OverviewType { MEAN, MIN, MAX }
